### ISSUE TITLE
Deliverable 1 Screenshot

### ISSUE THREAD

**Issue by Aleeya-Syed** [LUC-Intro-to-Web-Development/lab-1---version-control-practice-Aleeya-Syed#2]
<img width="458" alt="Screenshot 2022-11-10 at 5 20 41 PM" src="https://user-images.githubusercontent.com/93216865/201226487-5a5d921c-4fcb-46f4-9d19-e2ebed096564.png">

**Comment by instructorc** [comment]
Requirement met!
