### ISSUE TITLE
Deliverable 2 Screenshot

### ISSUE THREAD

**Issue by Aleeya-Syed** [LUC-Intro-to-Web-Development/lab-1---version-control-practice-Aleeya-Syed#3]
<img width="472" alt="Screenshot 2022-11-10 at 5 22 35 PM" src="https://user-images.githubusercontent.com/93216865/201226685-ff976a86-c31d-4dfd-80e6-e78fd90b85e3.png">

**Comment by instructorc** [comment]
Requirement met
